AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Authentication App Infrastructure

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues: [dev, staging, prod]
  JWTSecret:
    Type: String
    NoEcho: true
    Description: Secret key for JWT token signing

Globals:
  Function:
    Runtime: go1.x
    Timeout: 30
    Environment:
      Variables:
        USERS_TABLE: !Ref UsersTable
        JWT_SECRET: !Ref JWTSecret

Resources:
  # DynamoDB Table for Users
  UsersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub '${Environment}-auth-app-users'
      AttributeDefinitions:
        - AttributeName: email
          AttributeType: S
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: email
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: UserIdIndex
          KeySchema:
            - AttributeName: id
              KeyType: HASH
          Projection:
            ProjectionType: ALL
          BillingMode: PAY_PER_REQUEST
      BillingMode: PAY_PER_REQUEST
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true

  # API Gateway
  ApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref Environment
      Cors:
        AllowMethods: "'GET,POST,PUT,DELETE,OPTIONS'"
        AllowHeaders: "'Content-Type,Authorization'"
        AllowOrigin: "'*'"

  # Lambda Functions
  SignUpFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: auth/
      Handler: signup
      Events:
        SignUp:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /api/auth/signup
            Method: POST
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref UsersTable

  SignInFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: auth/
      Handler: signin
      Events:
        SignIn:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /api/auth/signin
            Method: POST
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref UsersTable

  SignOutFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: auth/
      Handler: signout
      Events:
        SignOut:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /api/auth/signout
            Method: POST

  MeFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: auth/
      Handler: me
      Events:
        Me:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /api/me
            Method: GET
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref UsersTable

  GetProfileFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: user/
      Handler: profile
      Events:
        GetProfile:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /user/profile
            Method: GET
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref UsersTable

  UpdateProfileFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: user/
      Handler: update-profile
      Events:
        UpdateProfile:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /user/profile
            Method: PUT
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref UsersTable

Outputs:
  ApiGatewayEndpoint:
    Description: API Gateway endpoint URL
    Value: !Sub 'https://${ApiGateway}.execute-api.${AWS::Region}.amazonaws.com/${Environment}'
    Export:
      Name: !Sub '${Environment}-auth-app-api-endpoint'

  UsersTableName:
    Description: DynamoDB Users table name
    Value: !Ref UsersTable
    Export:
      Name: !Sub '${Environment}-auth-app-users-table'